
export const LOAD_ACTIVITIES = 'LOAD_ACTIVITIES';

export const LOAD_ACTIVITY_TYPE_LISTS = 'LOAD_ACTIVITY_TYPE_LISTS';

export const LOAD_LATEST_ACTIVITIES = 'LOAD_LATEST_ACTIVITIES';

export const LOAD_ACTIVITY_INFO = 'LOAD_ACTIVITY_INFO';

export const LOAD_ACTIVITY_COMMENTS= 'LOAD_ACTIVITY_COMMENTS';
