export const LOAD_ACTIVITIES = 'LOAD_ACTIVITIES';
export const LOAD_ACTIVITY_DETAIL = 'LOAD_ACTIVITY_DETAIL';
export const LOAD_ENROLLED_LIST = 'LOAD_ENROLLED_LIST';
export const LOAD_ACTIVITY_WORKS = 'LOAD_ACTIVITY_WORKS';

export const LOAD_APPROVALS = 'LOAD_APPROVALS';
export const LOAD_APPROVAL_DETAIL = 'LOAD_APPROVAL_DETAIL';

export const LOAD_STUDENTS = 'LOAD_STUDENTS';
export const LOAD_MANAGERS = 'LOAD_MANAGERS';
