export const LOAD_USERINFO = 'LOAD_USERINFO';

export const LOAD_USERCOLLECTIONS = 'LOAD_USERCOLLECTIONS';

export const LOAD_USERENROLLED = 'LOAD_USERENROLLED';

export const LOAD_USERPUBLISHED = 'LOAD_USERPUBLISHED';